//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int proNo { get; set; }
        public string proName { get; set; }
        public string proDesc { get; set; }
        public Nullable<int> warrPeriod { get; set; }
        public string countryOrigion { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
